env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  { no-undef: off, no-console: off, import/extensions: [error, ignorePackages] }
