env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    max-len: off,
    no-undef: off,
    no-console: off,
    import/extensions: [error, ignorePackages],
  }
