# Name of workflow
name: CI

on:
  - push

env: 
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install, lint & project 
        run: |
          make install
          make lint
          make test
        - name: Test & publish code coverage
            Publish code coverage on Code Climate
            https://github.com/paambaati/codeclimate-action
          uses: paambaati/codeclimate-action@v4.0.0
           Add Code Climate secret key
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_API_KEY }}
          with:
            coverageCommand: make test-coverage
            debug: true
