name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install, test project
        run: |
          make install
          make test
        with:
          codeclimate_api_key: ${{ secrets.CODECLIMATE_API_KEY }}
       
